name: build
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: arduino/setup-arduino-cli@v1.1.1
      - name: install Arduino cores and libraries
        run: |
          arduino-cli version
          arduino-cli core update-index --additional-urls $ARDUINO_CORE_URI
          arduino-cli core install esp8266:esp8266 esp32:esp32 --additional-urls $ARDUINO_CORE_URI
        env:
          ARDUINO_CORE_URI: https://arduino.esp8266.com/stable/package_esp8266com_index.json,https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install esptool
      - uses: actions/checkout@v2
      - name: check code style
        run: |
          mk/format-code.sh
          [[ $(git status --porcelain | tee >(cat 1>&2) | wc -l) -eq 0 ]]
      - name: link library
        run: |
          mkdir -p $HOME/Arduino/libraries
          cd $HOME/Arduino/libraries
          ln -s $GITHUB_WORKSPACE WifiEspNow
      - name: compile in ESP8266
        run: |
          arduino-cli compile -b $FQBN examples/EspNowUnicast
          arduino-cli compile -b $FQBN examples/EspNowBroadcast
        env:
          FQBN: esp8266:esp8266:nodemcuv2
      - name: compile in ESP32
        run: |
          arduino-cli compile -b $FQBN examples/EspNowUnicast
          arduino-cli compile -b $FQBN examples/EspNowBroadcast
        env:
          FQBN: esp32:esp32:heltec_wifi_kit_32
